### ISSUE TITLE
Klipper configuration

### ISSUE THREAD

**Issue by ChellSol** [Pavulon87/GuiderII-klipper#1]
Hi
Is it possible to get a copy of your klipper configuration for the Guider 2 or can you direct me to a installation guide for the guider 2s ?

**Comment by Pavulon87** [comment]
I can, but installing klipper on guiderII it is not an easy task. It requires getting root access( https://github.com/Pavulon87/CrashForge ) and soldering 4 wires of USB to TTL converter directly to the board( RX, TX, GND and VCC near the STM32F103 chip). My config requires also swapping stepper drivers with TMC2208 and soldering UART pins. Additionally you neet to use klipper with ADS1118 support ( https://github.com/Pavulon87/klipper ).

**Comment by ChellSol** [comment]
oh really. I didn't think I would be that involved. Never mind. Thanks
